version: '3'
services:
  app:
    build: app/.
    depends_on:
      - mysql
    volumes:
      - ./app:/app

  mysql:
    build: mysql/.
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo
