version: '3'
services:
  app:
    build: app/.
    # command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - mysql
    volumes:
      - ./app:/app
    # ports:
    #   - "8000:8000"
    # environment:
    #   DATABASE_URL: postgres://todoapp@postgres/todos

  mysql:
    build: mysql/.
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdf
